/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefrigerationRouteImport } from './routes/refrigeration'
import { Route as LaundryRouteImport } from './routes/laundry'
import { Route as KitchenFabricationsRouteImport } from './routes/kitchen-fabrications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthRouteImport } from './routes/admin._auth'
import { Route as AdminAuthTestimonialsRouteImport } from './routes/admin._auth.testimonials'
import { Route as AdminAuthProductsRouteImport } from './routes/admin._auth.products'
import { Route as AdminAuthPortfolioRouteImport } from './routes/admin._auth.portfolio'
import { Route as AdminAuthMessagesRouteImport } from './routes/admin._auth.messages'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth.dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefrigerationRoute = RefrigerationRouteImport.update({
  id: '/refrigeration',
  path: '/refrigeration',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryRoute = LaundryRouteImport.update({
  id: '/laundry',
  path: '/laundry',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenFabricationsRoute = KitchenFabricationsRouteImport.update({
  id: '/kitchen-fabrications',
  path: '/kitchen-fabrications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthTestimonialsRoute = AdminAuthTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthProductsRoute = AdminAuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthPortfolioRoute = AdminAuthPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthMessagesRoute = AdminAuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/messages': typeof AdminAuthMessagesRoute
  '/admin/portfolio': typeof AdminAuthPortfolioRoute
  '/admin/products': typeof AdminAuthProductsRoute
  '/admin/testimonials': typeof AdminAuthTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/messages': typeof AdminAuthMessagesRoute
  '/admin/portfolio': typeof AdminAuthPortfolioRoute
  '/admin/products': typeof AdminAuthProductsRoute
  '/admin/testimonials': typeof AdminAuthTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/messages': typeof AdminAuthMessagesRoute
  '/admin/_auth/portfolio': typeof AdminAuthPortfolioRoute
  '/admin/_auth/products': typeof AdminAuthProductsRoute
  '/admin/_auth/testimonials': typeof AdminAuthTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/portfolio'
    | '/admin/products'
    | '/admin/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/portfolio'
    | '/admin/products'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
    | '/admin/_auth'
    | '/admin/login'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/messages'
    | '/admin/_auth/portfolio'
    | '/admin/_auth/products'
    | '/admin/_auth/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  KitchenFabricationsRoute: typeof KitchenFabricationsRoute
  LaundryRoute: typeof LaundryRoute
  RefrigerationRoute: typeof RefrigerationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refrigeration': {
      id: '/refrigeration'
      path: '/refrigeration'
      fullPath: '/refrigeration'
      preLoaderRoute: typeof RefrigerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry': {
      id: '/laundry'
      path: '/laundry'
      fullPath: '/laundry'
      preLoaderRoute: typeof LaundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-fabrications': {
      id: '/kitchen-fabrications'
      path: '/kitchen-fabrications'
      fullPath: '/kitchen-fabrications'
      preLoaderRoute: typeof KitchenFabricationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/testimonials': {
      id: '/admin/_auth/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAuthTestimonialsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/products': {
      id: '/admin/_auth/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAuthProductsRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/portfolio': {
      id: '/admin/_auth/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminAuthPortfolioRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/messages': {
      id: '/admin/_auth/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAuthMessagesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthMessagesRoute: typeof AdminAuthMessagesRoute
  AdminAuthPortfolioRoute: typeof AdminAuthPortfolioRoute
  AdminAuthProductsRoute: typeof AdminAuthProductsRoute
  AdminAuthTestimonialsRoute: typeof AdminAuthTestimonialsRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthMessagesRoute: AdminAuthMessagesRoute,
  AdminAuthPortfolioRoute: AdminAuthPortfolioRoute,
  AdminAuthProductsRoute: AdminAuthProductsRoute,
  AdminAuthTestimonialsRoute: AdminAuthTestimonialsRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  KitchenFabricationsRoute: KitchenFabricationsRoute,
  LaundryRoute: LaundryRoute,
  RefrigerationRoute: RefrigerationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
