/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefrigerationRouteImport } from './routes/refrigeration'
import { Route as LaundryRouteImport } from './routes/laundry'
import { Route as KitchenFabricationsRouteImport } from './routes/kitchen-fabrications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefrigerationRoute = RefrigerationRouteImport.update({
  id: '/refrigeration',
  path: '/refrigeration',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryRoute = LaundryRouteImport.update({
  id: '/laundry',
  path: '/laundry',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenFabricationsRoute = KitchenFabricationsRouteImport.update({
  id: '/kitchen-fabrications',
  path: '/kitchen-fabrications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/kitchen-fabrications': typeof KitchenFabricationsRoute
  '/laundry': typeof LaundryRoute
  '/refrigeration': typeof RefrigerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/kitchen-fabrications'
    | '/laundry'
    | '/refrigeration'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  KitchenFabricationsRoute: typeof KitchenFabricationsRoute
  LaundryRoute: typeof LaundryRoute
  RefrigerationRoute: typeof RefrigerationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refrigeration': {
      id: '/refrigeration'
      path: '/refrigeration'
      fullPath: '/refrigeration'
      preLoaderRoute: typeof RefrigerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry': {
      id: '/laundry'
      path: '/laundry'
      fullPath: '/laundry'
      preLoaderRoute: typeof LaundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-fabrications': {
      id: '/kitchen-fabrications'
      path: '/kitchen-fabrications'
      fullPath: '/kitchen-fabrications'
      preLoaderRoute: typeof KitchenFabricationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  KitchenFabricationsRoute: KitchenFabricationsRoute,
  LaundryRoute: LaundryRoute,
  RefrigerationRoute: RefrigerationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
